### PR TITLE
Update tokio to 1

### LINKED ISSUE #4: Does not actually work with Tokio 0.3
I tried this example from the README, using the latest async-compat, 0.1.5:
```rust
use async_compat::{Compat, CompatExt};

fn main() -> std::io::Result<()> {
    futures::executor::block_on(Compat::new(async {
        let stdin = tokio::io::stdin();
        let mut stdout = tokio::io::stdout();

        futures::io::copy(stdin.compat(), &mut stdout.compat_mut()).await?;
        Ok(())
    }))
}
```

When run with Tokio 0.2, it is fine. When run with Tokio 0.3, it fails with the following errors:
```
error[E0277]: the trait bound `tokio::io::Stdin: tokio::io::async_read::AsyncRead` is not satisfied
  --> src/main.rs:8:9
   |
8  |         futures::io::copy(stdin.compat(), &mut stdout.compat_mut()).compat().await?;
   |         ^^^^^^^^^^^^^^^^^ the trait `tokio::io::async_read::AsyncRead` is not implemented for `tokio::io::Stdin`
   | 
  ::: /home/chead/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/io/copy.rs:36:8
   |
36 |     R: AsyncRead,
   |        --------- required by this bound in `futures::io::copy`
   |
   = note: required because of the requirements on the impl of `futures::AsyncRead` for `async_compat::Compat<tokio::io::Stdin>`

error[E0277]: the trait bound `tokio::io::Stdout: tokio::io::async_write::AsyncWrite` is not satisfied
  --> src/main.rs:8:43
   |
8  |         futures::io::copy(stdin.compat(), &mut stdout.compat_mut()).compat().await?;
   |                                           ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `tokio::io::async_write::AsyncWrite` is not implemented for `tokio::io::Stdout`
   | 
  ::: /home/chead/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/io/copy.rs:37:8
   |
37 |     W: AsyncWrite + Unpin + ?Sized,
   |        ---------- required by this bound in `futures::io::copy`
   |
   = note: required because of the requirements on the impl of `tokio::io::async_write::AsyncWrite` for `&mut tokio::io::Stdout`
   = note: required because of the requirements on the impl of `futures::AsyncWrite` for `async_compat::Compat<&mut tokio::io::Stdout>`

error[E0277]: the trait bound `tokio::io::Stdin: tokio::io::async_read::AsyncRead` is not satisfied
 --> src/main.rs:8:9
  |
8 |         futures::io::copy(stdin.compat(), &mut stdout.compat_mut()).compat().await?;
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `tokio::io::async_read::AsyncRead` is not implemented for `tokio::io::Stdin`
  |
  = note: required because of the requirements on the impl of `futures::AsyncRead` for `async_compat::Compat<tokio::io::Stdin>`
  = note: required because of the requirements on the impl of `futures::Future` for `futures::io::Copy<'_, async_compat::Compat<tokio::io::Stdin>, async_compat::Compat<&mut tokio::io::Stdout>>`

error[E0277]: the trait bound `tokio::io::Stdout: tokio::io::async_write::AsyncWrite` is not satisfied
 --> src/main.rs:8:9
  |
8 |         futures::io::copy(stdin.compat(), &mut stdout.compat_mut()).compat().await?;
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `tokio::io::async_write::AsyncWrite` is not implemented for `tokio::io::Stdout`
  |
  = note: required because of the requirements on the impl of `tokio::io::async_write::AsyncWrite` for `&mut tokio::io::Stdout`
  = note: required because of the requirements on the impl of `futures::AsyncWrite` for `async_compat::Compat<&mut tokio::io::Stdout>`
  = note: required because of the requirements on the impl of `futures::Future` for `futures::io::Copy<'_, async_compat::Compat<tokio::io::Stdin>, async_compat::Compat<&mut tokio::io::Stdout>>`
```

### PR DESCRIPTION
**Pull request by taiki-e**
Closes #4

Note:

- this is a breaking change 
- this drops support for tokio 0.2/0.3 
- ~~ecosystem is still using tokio 0.2, so some examples are currently disabled~~

### CODE REVIEW

**Comment by taiki-e** [comment]
> * this drops support for tokio 0.2/0.3

An alternative to this is to use feature flags to support older tokio. 
I have no strong opinion as to which one to adopt. (Does anyone have an opinion on this?)

**Comment by ghost** [comment]
I think it's fine to support only tokio 1.0. Soon everyone will be using it.

**Comment by joshtriplett** [comment]
I think it makes sense for the current version of async-compat to only support tokio 1.0, as long as it makes a non-semver-compatible version bump in the process. That way, if people need to use a package that still depends on tokio 0.2, they can just use an older version of async-compat.

**Comment by taiki-e** [comment]
It's been about a month since I created this PR, and no one seems to oppose not supporting older versions. (And I think @joshtriplett's opinion makes a lot of sense)

@stjepang Could you review this? (A new version of warp has been released, and the last blocker has also been unblocked.)

**Review by ghost — APPROVED** [review]
LGTM

**Comment by taiki-e** [comment]
@stjepang Thanks for the review. I'll merge this and prepare for a new release.

**Comment by taiki-e** [comment]
Published in v0.2.0

File: src/lib.rs [hunk 1]
```diff
@@ -394,50 +400,30 @@ impl<T: tokio::io::AsyncSeek> futures_io::AsyncSeek for Compat<T> {
...
-        Poll::Ready(
-            self.project()
-                .seek_res
-                .take()
-                .unwrap_or(Err(io::ErrorKind::Other.into())),
-        )
+    fn poll_complete(mut self: Pin<&mut Self>, cx: &mut Context) -> Poll<io::Result<u64>> {
+        let seek_pos = self
+            .seek_pos
+            .expect("poll_complete called without start_seek being called first");
```
Comment (taiki-e) [inline src/lib.rs:411]: Hmm, this is not correct due to tokio 1.x AsyncSeek allows/recommends calling poll_complete before start_seek.
I'll send a fix.

Comment (taiki-e) [reply src/lib.rs:411]: Filed #12
