### ISSUE TITLE
Does not actually work with Tokio 0.3

### ISSUE THREAD

**Issue by Hawk777** [smol-rs/async-compat#4]
I tried this example from the README, using the latest async-compat, 0.1.5:
```rust
use async_compat::{Compat, CompatExt};

fn main() -> std::io::Result<()> {
    futures::executor::block_on(Compat::new(async {
        let stdin = tokio::io::stdin();
        let mut stdout = tokio::io::stdout();

        futures::io::copy(stdin.compat(), &mut stdout.compat_mut()).await?;
        Ok(())
    }))
}
```

When run with Tokio 0.2, it is fine. When run with Tokio 0.3, it fails with the following errors:
```
error[E0277]: the trait bound `tokio::io::Stdin: tokio::io::async_read::AsyncRead` is not satisfied
  --> src/main.rs:8:9
   |
8  |         futures::io::copy(stdin.compat(), &mut stdout.compat_mut()).compat().await?;
   |         ^^^^^^^^^^^^^^^^^ the trait `tokio::io::async_read::AsyncRead` is not implemented for `tokio::io::Stdin`
   | 
  ::: /home/chead/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/io/copy.rs:36:8
   |
36 |     R: AsyncRead,
   |        --------- required by this bound in `futures::io::copy`
   |
   = note: required because of the requirements on the impl of `futures::AsyncRead` for `async_compat::Compat<tokio::io::Stdin>`

error[E0277]: the trait bound `tokio::io::Stdout: tokio::io::async_write::AsyncWrite` is not satisfied
  --> src/main.rs:8:43
   |
8  |         futures::io::copy(stdin.compat(), &mut stdout.compat_mut()).compat().await?;
   |                                           ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `tokio::io::async_write::AsyncWrite` is not implemented for `tokio::io::Stdout`
   | 
  ::: /home/chead/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/io/copy.rs:37:8
   |
37 |     W: AsyncWrite + Unpin + ?Sized,
   |        ---------- required by this bound in `futures::io::copy`
   |
   = note: required because of the requirements on the impl of `tokio::io::async_write::AsyncWrite` for `&mut tokio::io::Stdout`
   = note: required because of the requirements on the impl of `futures::AsyncWrite` for `async_compat::Compat<&mut tokio::io::Stdout>`

error[E0277]: the trait bound `tokio::io::Stdin: tokio::io::async_read::AsyncRead` is not satisfied
 --> src/main.rs:8:9
  |
8 |         futures::io::copy(stdin.compat(), &mut stdout.compat_mut()).compat().await?;
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `tokio::io::async_read::AsyncRead` is not implemented for `tokio::io::Stdin`
  |
  = note: required because of the requirements on the impl of `futures::AsyncRead` for `async_compat::Compat<tokio::io::Stdin>`
  = note: required because of the requirements on the impl of `futures::Future` for `futures::io::Copy<'_, async_compat::Compat<tokio::io::Stdin>, async_compat::Compat<&mut tokio::io::Stdout>>`

error[E0277]: the trait bound `tokio::io::Stdout: tokio::io::async_write::AsyncWrite` is not satisfied
 --> src/main.rs:8:9
  |
8 |         futures::io::copy(stdin.compat(), &mut stdout.compat_mut()).compat().await?;
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `tokio::io::async_write::AsyncWrite` is not implemented for `tokio::io::Stdout`
  |
  = note: required because of the requirements on the impl of `tokio::io::async_write::AsyncWrite` for `&mut tokio::io::Stdout`
  = note: required because of the requirements on the impl of `futures::AsyncWrite` for `async_compat::Compat<&mut tokio::io::Stdout>`
  = note: required because of the requirements on the impl of `futures::Future` for `futures::io::Copy<'_, async_compat::Compat<tokio::io::Stdin>, async_compat::Compat<&mut tokio::io::Stdout>>`
```

**Comment by ghost** [comment]
Ah, you're right. What a mess this is :(

Honestly, I'll just wait for tokio 1.0 to get finalized and then update the compat layer. Until then, I recommend people to stick with tokio 0.2 or switch to any other runtime that is already at version 1.x

**Comment by joshtriplett** [comment]
async-compat currently depends on tokio 0.3, which means people currently using async-compat can't do `cargo update` without ending up with a version that depends on tokio 0.3, resulting in two versions of tokio in the dependency tree. As an interim step, would you consider either yanking the version that depends on tokio 0.3, or adding feature flags to control the versions of tokio that are pulled in as dependencies? (But if the tokio 0.3 support doesn't work yet, please consider just yanking it.)

**Comment by ghost** [comment]
Yanked version 0.1.5

**Comment by joshtriplett** [comment]
@stjepang Thank you; now I don't have to put `async-compat = "=0.1.4"` dependencies into projects.

**Comment by oblique** [comment]
@stjepang  Tokio 1.0.0 is released.

**Comment by taiki-e** [comment]
See #6 for tokio 1.0 support.
